language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  -  py.test --cov=test_junkie tests/
after_success:
  - coverage -t $CODECOV_TOKEN