language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - bash < (curl -s https://codecov.io/bash)